-- ═══════════════════════════════════════════════════════════
-- clevia Long-Tail-Migration: 461 wertvolle Stoffe → Server
-- ───────────────────────────────────────────────────────────
-- Diese seltenen, kuratierten Bewertungen verlassen den Client-Code
-- (F12-Schutz) und leben ab jetzt geschützt in clevia_stoffe.
-- Voraussetzung: stoff_db_schema.sql wurde ausgeführt.
-- Idempotent: ON CONFLICT (norm_key) DO UPDATE.
-- ═══════════════════════════════════════════════════════════

insert into clevia_stoffe (norm_key, d, i, a, k, g) values
  ('aprikosenkernöl', 'Aprikosenkernöl', 'Prunus Armeniaca Kernel Oil', 'gruen', 'Pflanzenöl', 'Aprikosenkernöl – reichhaltig, für trockene Haut'),
  ('prunus armeniaca kernel oil', 'Aprikosenkernöl', 'Prunus Armeniaca Kernel Oil', 'gruen', 'Pflanzenöl', 'Aprikosenkernöl – reichhaltig, für trockene Haut'),
  ('avocadoöl', 'Avocadoöl', 'Persea Gratissima Oil', 'gruen', 'Pflanzenöl', 'Avocadoöl – sehr reichhaltig, regenerierend'),
  ('persea gratissima oil', 'Avocadoöl', 'Persea Gratissima Oil', 'gruen', 'Pflanzenöl', 'Avocadoöl – sehr reichhaltig, regenerierend'),
  ('cocos nucifera oil', 'Kokosnussöl', 'Cocos Nucifera Oil', 'gruen', 'Pflanzenöl', 'Kokosöl – pflegend, leicht antimikrobiell'),
  ('butyrospermum parkii butter', 'Sheanussbutter', 'Butyrospermum Parkii Butter', 'gruen', 'Pflanzenbutter', 'Sheabutter – reichhaltig, schützend'),
  ('kakaobutter', 'Kakaobutter', 'Theobroma Cacao Seed Butter', 'gruen', 'Pflanzenbutter', 'Kakaobutter – reichhaltig, schützend'),
  ('theobroma cacao seed butter', 'Kakaobutter', 'Theobroma Cacao Seed Butter', 'gruen', 'Pflanzenbutter', 'Kakaobutter – reichhaltig, schützend'),
  ('mangobutter', 'Mangobutter', 'Mangifera Indica Seed Butter', 'gruen', 'Pflanzenbutter', 'Mangobutter – reichhaltig, nicht fettend'),
  ('mangifera indica seed butter', 'Mangobutter', 'Mangifera Indica Seed Butter', 'gruen', 'Pflanzenbutter', 'Mangobutter – reichhaltig, nicht fettend'),
  ('rizinusöl', 'Rizinusöl', 'Ricinus Communis Seed Oil', 'gruen', 'Pflanzenöl', 'Rizinusöl – pflegend, oft in Seifen und Haarpflege'),
  ('ricinus communis seed oil', 'Rizinusöl', 'Ricinus Communis Seed Oil', 'gruen', 'Pflanzenöl', 'Rizinusöl – pflegend, oft in Seifen und Haarpflege'),
  ('hanföl', 'Hanföl', 'Cannabis Sativa Seed Oil', 'gruen', 'Pflanzenöl', 'Hanfsamenöl – reich an Omega-3, entzündungshemmend'),
  ('cannabis sativa seed oil', 'Hanföl', 'Cannabis Sativa Seed Oil', 'gruen', 'Pflanzenöl', 'Hanfsamenöl – reich an Omega-3, entzündungshemmend'),
  ('nachtkerzenöl', 'Nachtkerzenöl', 'Oenothera Biennis Oil', 'gruen', 'Pflanzenöl', 'Nachtkerzenöl – bei trockener, empfindlicher Haut'),
  ('oenothera biennis oil', 'Nachtkerzenöl', 'Oenothera Biennis Oil', 'gruen', 'Pflanzenöl', 'Nachtkerzenöl – bei trockener, empfindlicher Haut'),
  ('traubenkernöl', 'Traubenkernöl', 'Vitis Vinifera Seed Oil', 'gelb', 'Pflanzenöl', 'Traubenkernöl – leicht, aber hoher Omega-6-Anteil'),
  ('vitis vinifera seed oil', 'Traubenkernöl', 'Vitis Vinifera Seed Oil', 'gelb', 'Pflanzenöl', 'Traubenkernöl – leicht, aber hoher Omega-6-Anteil'),
  ('sesamöl', 'Sesamöl', 'Sesamum Indicum Seed Oil', 'gruen', 'Pflanzenöl', 'Sesamöl – wärmend, traditionell im Ayurveda'),
  ('sesamum indicum seed oil', 'Sesamöl', 'Sesamum Indicum Seed Oil', 'gruen', 'Pflanzenöl', 'Sesamöl – wärmend, traditionell im Ayurveda'),
  ('distelöl', 'Distelöl', 'Carthamus Tinctorius Seed Oil', 'gelb', 'Pflanzenöl', 'Distelöl – leicht, hoher Omega-6-Anteil'),
  ('carthamus tinctorius seed oil', 'Distelöl', 'Carthamus Tinctorius Seed Oil', 'gelb', 'Pflanzenöl', 'Distelöl – leicht, hoher Omega-6-Anteil'),
  ('leinöl', 'Leinöl', 'Linum Usitatissimum Seed Oil', 'gruen', 'Pflanzenöl', 'Leinöl – sehr hoher Omega-3-Gehalt'),
  ('linum usitatissimum seed oil', 'Leinöl', 'Linum Usitatissimum Seed Oil', 'gruen', 'Pflanzenöl', 'Leinöl – sehr hoher Omega-3-Gehalt'),
  ('hagebuttenöl', 'Hagebuttenöl', 'Rosa Canina Fruit Oil', 'gruen', 'Pflanzenöl', 'Wildrosenöl – regenerierend, bei Narben'),
  ('rosa canina fruit oil', 'Hagebuttenöl', 'Rosa Canina Fruit Oil', 'gruen', 'Pflanzenöl', 'Wildrosenöl – regenerierend, bei Narben'),
  ('wildrosenöl', 'Wildrosenöl', 'Rosa Moschata Seed Oil', 'gruen', 'Pflanzenöl', 'Hagebuttenkernöl – zellregenerierend'),
  ('rosa moschata seed oil', 'Wildrosenöl', 'Rosa Moschata Seed Oil', 'gruen', 'Pflanzenöl', 'Hagebuttenkernöl – zellregenerierend'),
  ('marulaöl', 'Marulaöl', 'Sclerocarya Birrea Seed Oil', 'gruen', 'Pflanzenöl', 'Marulaöl – antioxidativ, schnell einziehend'),
  ('sclerocarya birrea seed oil', 'Marulaöl', 'Sclerocarya Birrea Seed Oil', 'gruen', 'Pflanzenöl', 'Marulaöl – antioxidativ, schnell einziehend'),
  ('macadamiaöl', 'Macadamiaöl', 'Macadamia Ternifolia Seed Oil', 'gruen', 'Pflanzenöl', 'Macadamianussöl – reichhaltig, hautähnlich'),
  ('macadamia ternifolia seed oil', 'Macadamiaöl', 'Macadamia Ternifolia Seed Oil', 'gruen', 'Pflanzenöl', 'Macadamianussöl – reichhaltig, hautähnlich'),
  ('kürbiskernöl', 'Kürbiskernöl', 'Cucurbita Pepo Seed Oil', 'gruen', 'Pflanzenöl', 'Kürbiskernöl – nährstoffreich'),
  ('cucurbita pepo seed oil', 'Kürbiskernöl', 'Cucurbita Pepo Seed Oil', 'gruen', 'Pflanzenöl', 'Kürbiskernöl – nährstoffreich'),
  ('schwarzkümmelöl', 'Schwarzkümmelöl', 'Nigella Sativa Seed Oil', 'gruen', 'Pflanzenöl', 'Schwarzkümmelöl – entzündungshemmend, bei Hautproblemen'),
  ('nigella sativa seed oil', 'Schwarzkümmelöl', 'Nigella Sativa Seed Oil', 'gruen', 'Pflanzenöl', 'Schwarzkümmelöl – entzündungshemmend, bei Hautproblemen'),
  ('babassuöl', 'Babassuöl', 'Orbignya Oleifera Seed Oil', 'gruen', 'Pflanzenöl', 'Babassuöl – leicht, ähnlich Kokosöl'),
  ('orbignya oleifera seed oil', 'Babassuöl', 'Orbignya Oleifera Seed Oil', 'gruen', 'Pflanzenöl', 'Babassuöl – leicht, ähnlich Kokosöl'),
  ('camelinaöl', 'Camelinaöl', 'Camelina Sativa Seed Oil', 'gruen', 'Pflanzenöl', 'Leindotteröl – reich an Omega-3'),
  ('camelina sativa seed oil', 'Camelinaöl', 'Camelina Sativa Seed Oil', 'gruen', 'Pflanzenöl', 'Leindotteröl – reich an Omega-3'),
  ('borretschöl', 'Borretschöl', 'Borago Officinalis Seed Oil', 'gruen', 'Pflanzenöl', 'Borretschöl – hoher Gamma-Linolensäure-Gehalt'),
  ('borago officinalis seed oil', 'Borretschöl', 'Borago Officinalis Seed Oil', 'gruen', 'Pflanzenöl', 'Borretschöl – hoher Gamma-Linolensäure-Gehalt'),
  ('reiskeimöl', 'Reiskeimöl', 'Oryza Sativa Bran Oil', 'gruen', 'Pflanzenöl', 'Reiskleieöl – antioxidativ, mit Vitamin E'),
  ('oryza sativa bran oil', 'Reiskeimöl', 'Oryza Sativa Bran Oil', 'gruen', 'Pflanzenöl', 'Reiskleieöl – antioxidativ, mit Vitamin E'),
  ('baobaböl', 'Baobaböl', 'Adansonia Digitata Seed Oil', 'gruen', 'Pflanzenöl', 'Baobaböl – reichhaltig, regenerierend'),
  ('adansonia digitata seed oil', 'Baobaböl', 'Adansonia Digitata Seed Oil', 'gruen', 'Pflanzenöl', 'Baobaböl – reichhaltig, regenerierend'),
  ('bienenwachs', 'Bienenwachs', 'Cera Alba', 'gruen', 'Wachs', 'Bienenwachs – schützend, in Salben und Balsamen'),
  ('cera alba', 'Bienenwachs', 'Cera Alba', 'gruen', 'Wachs', 'Bienenwachs – schützend, in Salben und Balsamen'),
  ('candelillawachs', 'Candelillawachs', 'Euphorbia Cerifera Cera', 'gruen', 'Wachs', 'Candelillawachs – pflanzlich, in Lippenpflege'),
  ('euphorbia cerifera cera', 'Candelillawachs', 'Euphorbia Cerifera Cera', 'gruen', 'Wachs', 'Candelillawachs – pflanzlich, in Lippenpflege')
on conflict (norm_key) do update set d=excluded.d, i=excluded.i, a=excluded.a, k=excluded.k, g=excluded.g;

insert into clevia_stoffe (norm_key, d, i, a, k, g) values
  ('carnaubawachs', 'Carnaubawachs', 'Copernicia Cerifera Cera', 'gruen', 'Wachs', 'Carnaubawachs – pflanzlich, härtend'),
  ('copernicia cerifera cera', 'Carnaubawachs', 'Copernicia Cerifera Cera', 'gruen', 'Wachs', 'Carnaubawachs – pflanzlich, härtend'),
  ('sonnenblumenwachs', 'Sonnenblumenwachs', 'Helianthus Annuus Seed Wax', 'gruen', 'Wachs', 'Sonnenblumenwachs – pflanzlicher Konsistenzgeber'),
  ('helianthus annuus seed wax', 'Sonnenblumenwachs', 'Helianthus Annuus Seed Wax', 'gruen', 'Wachs', 'Sonnenblumenwachs – pflanzlicher Konsistenzgeber'),
  ('lanolin', 'Lanolin', 'Lanolin', 'gelb', 'Wachs', 'Wollwachs – stark pflegend, aber mögliches Allergen'),
  ('lavendelöl', 'Lavendelöl', 'Lavandula Angustifolia Oil', 'gruen', 'Ätherisches Öl', 'Lavendelöl – beruhigend (enthält natürliche Allergene wie Linalool)'),
  ('lavandula angustifolia oil', 'Lavendelöl', 'Lavandula Angustifolia Oil', 'gruen', 'Ätherisches Öl', 'Lavendelöl – beruhigend (enthält natürliche Allergene wie Linalool)'),
  ('teebaumöl', 'Teebaumöl', 'Melaleuca Alternifolia Leaf Oil', 'gruen', 'Ätherisches Öl', 'Teebaumöl – antibakteriell, bei unreiner Haut'),
  ('melaleuca alternifolia leaf oil', 'Teebaumöl', 'Melaleuca Alternifolia Leaf Oil', 'gruen', 'Ätherisches Öl', 'Teebaumöl – antibakteriell, bei unreiner Haut'),
  ('rosmarinöl', 'Rosmarinöl', 'Rosmarinus Officinalis Leaf Oil', 'gruen', 'Ätherisches Öl', 'Rosmarinöl – durchblutungsfördernd, anregend'),
  ('rosmarinus officinalis leaf oil', 'Rosmarinöl', 'Rosmarinus Officinalis Leaf Oil', 'gruen', 'Ätherisches Öl', 'Rosmarinöl – durchblutungsfördernd, anregend'),
  ('pfefferminzöl', 'Pfefferminzöl', 'Mentha Piperita Oil', 'gruen', 'Ätherisches Öl', 'Pfefferminzöl – kühlend, erfrischend'),
  ('mentha piperita oil', 'Pfefferminzöl', 'Mentha Piperita Oil', 'gruen', 'Ätherisches Öl', 'Pfefferminzöl – kühlend, erfrischend'),
  ('zitronenöl', 'Zitronenöl', 'Citrus Limon Peel Oil', 'gelb', 'Ätherisches Öl', 'Zitronenöl – erfrischend, aber phototoxisch (Sonne meiden)'),
  ('citrus limon peel oil', 'Zitronenöl', 'Citrus Limon Peel Oil', 'gelb', 'Ätherisches Öl', 'Zitronenöl – erfrischend, aber phototoxisch (Sonne meiden)'),
  ('orangenöl', 'Orangenöl', 'Citrus Aurantium Dulcis Peel Oil', 'gelb', 'Ätherisches Öl', 'Orangenöl – aufhellend, leicht phototoxisch'),
  ('citrus aurantium dulcis peel oil', 'Orangenöl', 'Citrus Aurantium Dulcis Peel Oil', 'gelb', 'Ätherisches Öl', 'Orangenöl – aufhellend, leicht phototoxisch'),
  ('eukalyptusöl', 'Eukalyptusöl', 'Eucalyptus Globulus Leaf Oil', 'gruen', 'Ätherisches Öl', 'Eukalyptusöl – befreiend, bei Erkältung'),
  ('eucalyptus globulus leaf oil', 'Eukalyptusöl', 'Eucalyptus Globulus Leaf Oil', 'gruen', 'Ätherisches Öl', 'Eukalyptusöl – befreiend, bei Erkältung'),
  ('kamillenöl', 'Kamillenöl', 'Chamomilla Recutita Flower Oil', 'gruen', 'Ätherisches Öl', 'Kamillenöl – beruhigend, entzündungshemmend'),
  ('chamomilla recutita flower oil', 'Kamillenöl', 'Chamomilla Recutita Flower Oil', 'gruen', 'Ätherisches Öl', 'Kamillenöl – beruhigend, entzündungshemmend'),
  ('rosenöl', 'Rosenöl', 'Rosa Damascena Flower Oil', 'gruen', 'Ätherisches Öl', 'Rosenöl – pflegend, für reife Haut'),
  ('rosa damascena flower oil', 'Rosenöl', 'Rosa Damascena Flower Oil', 'gruen', 'Ätherisches Öl', 'Rosenöl – pflegend, für reife Haut'),
  ('geranienöl', 'Geranienöl', 'Pelargonium Graveolens Oil', 'gruen', 'Ätherisches Öl', 'Geranienöl – ausgleichend, blumig'),
  ('pelargonium graveolens oil', 'Geranienöl', 'Pelargonium Graveolens Oil', 'gruen', 'Ätherisches Öl', 'Geranienöl – ausgleichend, blumig'),
  ('ylang ylang öl', 'Ylang-Ylang-Öl', 'Cananga Odorata Flower Oil', 'gruen', 'Ätherisches Öl', 'Ylang-Ylang – entspannend, blumig-süß'),
  ('cananga odorata flower oil', 'Ylang-Ylang-Öl', 'Cananga Odorata Flower Oil', 'gruen', 'Ätherisches Öl', 'Ylang-Ylang – entspannend, blumig-süß'),
  ('weihrauchöl', 'Weihrauchöl', 'Boswellia Carterii Oil', 'gruen', 'Ätherisches Öl', 'Weihrauchöl – regenerierend, für reife Haut'),
  ('boswellia carterii oil', 'Weihrauchöl', 'Boswellia Carterii Oil', 'gruen', 'Ätherisches Öl', 'Weihrauchöl – regenerierend, für reife Haut'),
  ('sandelholzöl', 'Sandelholzöl', 'Santalum Album Oil', 'gruen', 'Ätherisches Öl', 'Sandelholzöl – beruhigend, holzig'),
  ('santalum album oil', 'Sandelholzöl', 'Santalum Album Oil', 'gruen', 'Ätherisches Öl', 'Sandelholzöl – beruhigend, holzig'),
  ('bergamotteöl', 'Bergamotteöl', 'Citrus Aurantium Bergamia Peel Oil', 'gelb', 'Ätherisches Öl', 'Bergamotteöl – stimmungshebend, stark phototoxisch'),
  ('citrus aurantium bergamia peel oil', 'Bergamotteöl', 'Citrus Aurantium Bergamia Peel Oil', 'gelb', 'Ätherisches Öl', 'Bergamotteöl – stimmungshebend, stark phototoxisch'),
  ('zedernholzöl', 'Zedernholzöl', 'Cedrus Atlantica Wood Oil', 'gruen', 'Ätherisches Öl', 'Zedernholzöl – erdend, holzig'),
  ('cedrus atlantica wood oil', 'Zedernholzöl', 'Cedrus Atlantica Wood Oil', 'gruen', 'Ätherisches Öl', 'Zedernholzöl – erdend, holzig'),
  ('thymianöl', 'Thymianöl', 'Thymus Vulgaris Oil', 'gruen', 'Ätherisches Öl', 'Thymianöl – antibakteriell, kräftig'),
  ('thymus vulgaris oil', 'Thymianöl', 'Thymus Vulgaris Oil', 'gruen', 'Ätherisches Öl', 'Thymianöl – antibakteriell, kräftig'),
  ('salbeiöl', 'Salbeiöl', 'Salvia Officinalis Oil', 'gruen', 'Ätherisches Öl', 'Salbeiöl – klärend, adstringierend'),
  ('salvia officinalis oil', 'Salbeiöl', 'Salvia Officinalis Oil', 'gruen', 'Ätherisches Öl', 'Salbeiöl – klärend, adstringierend'),
  ('ringelblume', 'Ringelblume', 'Calendula Officinalis Flower Extract', 'gruen', 'Pflanzenextrakt', 'Ringelblume – wundheilend, beruhigend'),
  ('calendula officinalis flower extract', 'Ringelblumenblüte', 'Calendula Officinalis Flower Extract', 'gruen', 'Pflanzenextrakt', 'Ringelblume – wundheilend'),
  ('kamille', 'Kamille', 'Chamomilla Recutita Flower Extract', 'gruen', 'Pflanzenextrakt', 'Kamille – beruhigend, entzündungshemmend'),
  ('chamomilla recutita flower extract', 'Kamille', 'Chamomilla Recutita Flower Extract', 'gruen', 'Pflanzenextrakt', 'Kamille – beruhigend, entzündungshemmend'),
  ('aloe vera', 'Aloe Vera', 'Aloe Barbadensis Leaf Juice', 'gruen', 'Pflanzenextrakt', 'Aloe Vera – kühlend, feuchtigkeitsspendend'),
  ('aloe barbadensis leaf juice', 'Aloe Vera', 'Aloe Barbadensis Leaf Juice', 'gruen', 'Pflanzenextrakt', 'Aloe Vera – kühlend, feuchtigkeitsspendend'),
  ('grüner tee', 'Grüner Tee', 'Camellia Sinensis Leaf Extract', 'gruen', 'Pflanzenextrakt', 'Grüner Tee – antioxidativ, schützend'),
  ('camellia sinensis leaf extract', 'Grüner Tee', 'Camellia Sinensis Leaf Extract', 'gruen', 'Pflanzenextrakt', 'Grüner Tee – antioxidativ, schützend'),
  ('hafer', 'Hafer', 'Oats', 'gruen', 'Getreide', 'Hafer – ballaststoffreich, sättigend'),
  ('avena sativa kernel extract', 'Hafer', 'Avena Sativa Kernel Extract', 'gruen', 'Pflanzenextrakt', 'Hafer – beruhigend, bei empfindlicher/juckender Haut'),
  ('ringelblumenextrakt', 'Ringelblumenextrakt', 'Calendula Officinalis Extract', 'gruen', 'Pflanzenextrakt', 'Ringelblume – wundheilend, beruhigend')
on conflict (norm_key) do update set d=excluded.d, i=excluded.i, a=excluded.a, k=excluded.k, g=excluded.g;

insert into clevia_stoffe (norm_key, d, i, a, k, g) values
  ('calendula officinalis extract', 'Ringelblumenextrakt', 'Calendula Officinalis Extract', 'gruen', 'Pflanzenextrakt', 'Ringelblume – wundheilend, beruhigend'),
  ('gurke', 'Gurke', 'Cucumis Sativus Fruit Extract', 'gruen', 'Pflanzenextrakt', 'Gurkenextrakt – erfrischend, abschwellend'),
  ('cucumis sativus fruit extract', 'Gurke', 'Cucumis Sativus Fruit Extract', 'gruen', 'Pflanzenextrakt', 'Gurkenextrakt – erfrischend, abschwellend'),
  ('sanddorn', 'Sanddorn', 'Hippophae Rhamnoides Extract', 'gruen', 'Pflanzenextrakt', 'Sanddorn – vitaminreich, regenerierend'),
  ('hippophae rhamnoides extract', 'Sanddorn', 'Hippophae Rhamnoides Extract', 'gruen', 'Pflanzenextrakt', 'Sanddorn – vitaminreich, regenerierend'),
  ('ginkgo', 'Ginkgo', 'Ginkgo Biloba Leaf Extract', 'gruen', 'Pflanzenextrakt', 'Ginkgo – durchblutungsfördernd, antioxidativ'),
  ('ginkgo biloba leaf extract', 'Ginkgo', 'Ginkgo Biloba Leaf Extract', 'gruen', 'Pflanzenextrakt', 'Ginkgo – durchblutungsfördernd, antioxidativ'),
  ('rosmarinextrakt', 'Rosmarinextrakt', 'Rosmarinus Officinalis Leaf Extract', 'gruen', 'Pflanzenextrakt', 'Rosmarin – antioxidativ, anregend'),
  ('rosmarinus officinalis leaf extract', 'Rosmarinextrakt', 'Rosmarinus Officinalis Leaf Extract', 'gruen', 'Pflanzenextrakt', 'Rosmarin – antioxidativ, anregend'),
  ('brennnessel', 'Brennnessel', 'Urtica Dioica Extract', 'gruen', 'Pflanzenextrakt', 'Brennnessel – klärend, bei fettiger Haut/Kopfhaut'),
  ('urtica dioica extract', 'Brennnessel', 'Urtica Dioica Extract', 'gruen', 'Pflanzenextrakt', 'Brennnessel – klärend, bei fettiger Haut/Kopfhaut'),
  ('schachtelhalm', 'Schachtelhalm', 'Equisetum Arvense Extract', 'gruen', 'Pflanzenextrakt', 'Ackerschachtelhalm – stärkend, mit Kieselsäure'),
  ('equisetum arvense extract', 'Schachtelhalm', 'Equisetum Arvense Extract', 'gruen', 'Pflanzenextrakt', 'Ackerschachtelhalm – stärkend, mit Kieselsäure'),
  ('efeu', 'Efeu', 'Hedera Helix Extract', 'gruen', 'Pflanzenextrakt', 'Efeuextrakt – straffend, oft in Anti-Cellulite'),
  ('hedera helix extract', 'Efeu', 'Hedera Helix Extract', 'gruen', 'Pflanzenextrakt', 'Efeuextrakt – straffend, oft in Anti-Cellulite'),
  ('arnika', 'Arnika', 'Arnica Montana Flower Extract', 'gruen', 'Pflanzenextrakt', 'Arnika – abschwellend, bei Prellungen'),
  ('arnica montana flower extract', 'Arnika', 'Arnica Montana Flower Extract', 'gruen', 'Pflanzenextrakt', 'Arnika – abschwellend, bei Prellungen'),
  ('malve', 'Malve', 'Malva Sylvestris Extract', 'gruen', 'Pflanzenextrakt', 'Malve – reizlindernd, schützend'),
  ('malva sylvestris extract', 'Malve', 'Malva Sylvestris Extract', 'gruen', 'Pflanzenextrakt', 'Malve – reizlindernd, schützend'),
  ('lindenblüte', 'Lindenblüte', 'Tilia Cordata Flower Extract', 'gruen', 'Pflanzenextrakt', 'Lindenblüte – beruhigend, mild'),
  ('tilia cordata flower extract', 'Lindenblüte', 'Tilia Cordata Flower Extract', 'gruen', 'Pflanzenextrakt', 'Lindenblüte – beruhigend, mild'),
  ('johanniskraut', 'Johanniskraut', 'Hypericum Perforatum Extract', 'gruen', 'Pflanzenextrakt', 'Johanniskraut – reizlindernd (phototoxisch beachten)'),
  ('hypericum perforatum extract', 'Johanniskraut', 'Hypericum Perforatum Extract', 'gruen', 'Pflanzenextrakt', 'Johanniskraut – reizlindernd (phototoxisch beachten)'),
  ('rosskastanie', 'Rosskastanie', 'Aesculus Hippocastanum Extract', 'gruen', 'Pflanzenextrakt', 'Rosskastanie – gefäßstärkend, bei Couperose'),
  ('aesculus hippocastanum extract', 'Rosskastanie', 'Aesculus Hippocastanum Extract', 'gruen', 'Pflanzenextrakt', 'Rosskastanie – gefäßstärkend, bei Couperose'),
  ('centella', 'Centella', 'Centella Asiatica Extract', 'gruen', 'Pflanzenextrakt', 'Tigergras – regenerierend, beruhigend (Cica)'),
  ('centella asiatica extract', 'Centella', 'Centella Asiatica Extract', 'gruen', 'Pflanzenextrakt', 'Tigergras – regenerierend, beruhigend (Cica)'),
  ('süßholzwurzel', 'Süßholzwurzel', 'Glycyrrhiza Glabra Root Extract', 'gruen', 'Pflanzenextrakt', 'Süßholz – aufhellend, entzündungshemmend'),
  ('glycyrrhiza glabra root extract', 'Süßholzwurzel', 'Glycyrrhiza Glabra Root Extract', 'gruen', 'Pflanzenextrakt', 'Süßholz – aufhellend, entzündungshemmend'),
  ('hibiskus', 'Hibiskus', 'Hibiscus Sabdariffa Flower Extract', 'gruen', 'Pflanzenextrakt', 'Hibiskus – antioxidativ, mit Fruchtsäuren'),
  ('hibiscus sabdariffa flower extract', 'Hibiskus', 'Hibiscus Sabdariffa Flower Extract', 'gruen', 'Pflanzenextrakt', 'Hibiskus – antioxidativ, mit Fruchtsäuren'),
  ('granatapfel', 'Granatapfel', 'Punica Granatum Extract', 'gruen', 'Pflanzenextrakt', 'Granatapfel – stark antioxidativ'),
  ('punica granatum extract', 'Granatapfel', 'Punica Granatum Extract', 'gruen', 'Pflanzenextrakt', 'Granatapfel – stark antioxidativ'),
  ('traubenkern', 'Traubenkern', 'Vitis Vinifera Seed Extract', 'gruen', 'Pflanzenextrakt', 'Traubenkernextrakt – antioxidativ (OPC)'),
  ('vitis vinifera seed extract', 'Traubenkern', 'Vitis Vinifera Seed Extract', 'gruen', 'Pflanzenextrakt', 'Traubenkernextrakt – antioxidativ (OPC)'),
  ('ackerstiefmütterchen', 'Ackerstiefmütterchen', 'Viola Tricolor Extract', 'gruen', 'Pflanzenextrakt', 'Stiefmütterchen – reizlindernd, bei unreiner Haut'),
  ('viola tricolor extract', 'Ackerstiefmütterchen', 'Viola Tricolor Extract', 'gruen', 'Pflanzenextrakt', 'Stiefmütterchen – reizlindernd, bei unreiner Haut'),
  ('ringelblumenblüte', 'Ringelblumenblüte', 'Calendula Officinalis Flower Extract', 'gruen', 'Pflanzenextrakt', 'Ringelblume – wundheilend'),
  ('bambus', 'Bambus', 'Bambusa Vulgaris Extract', 'gruen', 'Pflanzenextrakt', 'Bambusextrakt – mit Kieselsäure, stärkend'),
  ('bambusa vulgaris extract', 'Bambus', 'Bambusa Vulgaris Extract', 'gruen', 'Pflanzenextrakt', 'Bambusextrakt – mit Kieselsäure, stärkend'),
  ('honig', 'Honig', 'Honey', 'gruen', 'Süßungsmittel', 'Honig – natürliches Süßungsmittel'),
  ('mel', 'Honig', 'Mel', 'gruen', 'Naturstoff', 'Honig – feuchtigkeitsspendend, antibakteriell'),
  ('propolis', 'Propolis', 'Propolis Extract', 'gruen', 'Naturstoff', 'Propolis – antibakteriell, wundheilend'),
  ('propolis extract', 'Propolis', 'Propolis Extract', 'gruen', 'Naturstoff', 'Propolis – antibakteriell, wundheilend'),
  ('gelée royale', 'Gelée Royale', 'Royal Jelly', 'gruen', 'Naturstoff', 'Gelée Royale – nährend, für reife Haut'),
  ('royal jelly', 'Gelée Royale', 'Royal Jelly', 'gruen', 'Naturstoff', 'Gelée Royale – nährend, für reife Haut'),
  ('milchsäure', 'Milchsäure', 'Lactic Acid', 'gruen', 'Wirkstoff', 'Milchsäure – mildes Peeling, natürlich in der Haut (NMF)'),
  ('lactic acid', 'Milchsäure', 'Lactic Acid', 'gruen', 'Wirkstoff', 'Milchsäure – mildes Peeling, natürlich in der Haut (NMF)'),
  ('hyaluronsäure', 'Hyaluronsäure', 'Hyaluronic Acid', 'gruen', 'Wirkstoff', 'Hyaluronsäure – bindet Feuchtigkeit'),
  ('hyaluronic acid', 'Hyaluronsäure', 'Hyaluronic Acid', 'gruen', 'Wirkstoff', 'Hyaluronsäure – bindet Feuchtigkeit')
on conflict (norm_key) do update set d=excluded.d, i=excluded.i, a=excluded.a, k=excluded.k, g=excluded.g;

insert into clevia_stoffe (norm_key, d, i, a, k, g) values
  ('squalan', 'Squalan', 'Squalane', 'gruen', 'Wirkstoff', 'Squalan (pflanzlich) – hautähnlich, sehr verträglich'),
  ('squalane', 'Squalan', 'Squalane', 'gruen', 'Wirkstoff', 'Squalan (pflanzlich) – hautähnlich, sehr verträglich'),
  ('bisabolol', 'Bisabolol', 'Bisabolol', 'gruen', 'Wirkstoff', 'Bisabolol – Kamillenwirkstoff, beruhigend'),
  ('vitamin c', 'Vitamin C', 'Ascorbic Acid', 'gruen', 'Wirkstoff', 'Vitamin C – Antioxidans, aufhellend'),
  ('ascorbic acid', 'Vitamin C', 'Ascorbic Acid', 'gruen', 'Wirkstoff', 'Vitamin C – Antioxidans, aufhellend'),
  ('niacinamid', 'Niacinamid', 'Niacinamide', 'gruen', 'Wirkstoff', 'Vitamin B3 – ausgleichend, bei unreiner Haut'),
  ('niacinamide', 'Niacinamid', 'Niacinamide', 'gruen', 'Wirkstoff', 'Vitamin B3 – ausgleichend, bei unreiner Haut'),
  ('koriander', 'Koriander', 'Coriander', 'gruen', 'Gewürz', 'Koriander – Gewürz/Kraut, unbedenklich'),
  ('coriander', 'Koriander', 'Coriander', 'gruen', 'Gewürz', 'Koriander – Gewürz/Kraut, unbedenklich'),
  ('kreuzkümmel', 'Kreuzkümmel', 'Cumin', 'gruen', 'Gewürz', 'Kreuzkümmel (Cumin) – Gewürz, unbedenklich'),
  ('cumin', 'Kreuzkümmel', 'Cumin', 'gruen', 'Gewürz', 'Kreuzkümmel (Cumin) – Gewürz, unbedenklich'),
  ('kurkuma', 'Kurkuma', 'Turmeric', 'gruen', 'Gewürz', 'Kurkuma – Gewürz, entzündungshemmend'),
  ('turmeric', 'Kurkuma', 'Turmeric', 'gruen', 'Gewürz', 'Kurkuma – Gewürz, entzündungshemmend'),
  ('ingwer', 'Ingwer', 'Ginger', 'gruen', 'Gewürz', 'Ingwer – wärmend, verdauungsfördernd'),
  ('ginger', 'Ingwer', 'Ginger', 'gruen', 'Gewürz', 'Ingwer – wärmend, verdauungsfördernd'),
  ('zimt', 'Zimt', 'Cinnamon', 'gruen', 'Gewürz', 'Zimt – Gewürz (Ceylon bevorzugen, weniger Cumarin)'),
  ('cinnamon', 'Zimt', 'Cinnamon', 'gruen', 'Gewürz', 'Zimt – Gewürz (Ceylon bevorzugen, weniger Cumarin)'),
  ('paprika', 'Paprika', 'Paprika', 'gruen', 'Gewürz', 'Paprikapulver – Gewürz, unbedenklich'),
  ('pfeffer', 'Pfeffer', 'Pepper', 'gruen', 'Gewürz', 'Pfeffer – Gewürz, unbedenklich'),
  ('pepper', 'Pfeffer', 'Pepper', 'gruen', 'Gewürz', 'Pfeffer – Gewürz, unbedenklich'),
  ('muskat', 'Muskat', 'Nutmeg', 'gruen', 'Gewürz', 'Muskatnuss – Gewürz, in Maßen'),
  ('nutmeg', 'Muskat', 'Nutmeg', 'gruen', 'Gewürz', 'Muskatnuss – Gewürz, in Maßen'),
  ('oregano', 'Oregano', 'Oregano', 'gruen', 'Gewürz', 'Oregano – Kraut, antioxidativ'),
  ('basilikum', 'Basilikum', 'Basil', 'gruen', 'Gewürz', 'Basilikum – Kraut, unbedenklich'),
  ('basil', 'Basilikum', 'Basil', 'gruen', 'Gewürz', 'Basilikum – Kraut, unbedenklich'),
  ('thymian', 'Thymian', 'Thyme', 'gruen', 'Gewürz', 'Thymian – Kraut, unbedenklich'),
  ('thyme', 'Thymian', 'Thyme', 'gruen', 'Gewürz', 'Thymian – Kraut, unbedenklich'),
  ('rosmarin', 'Rosmarin', 'Rosemary', 'gruen', 'Gewürz', 'Rosmarin – Kraut, antioxidativ'),
  ('rosemary', 'Rosmarin', 'Rosemary', 'gruen', 'Gewürz', 'Rosmarin – Kraut, antioxidativ'),
  ('petersilie', 'Petersilie', 'Parsley', 'gruen', 'Gewürz', 'Petersilie – Kraut, vitaminreich'),
  ('parsley', 'Petersilie', 'Parsley', 'gruen', 'Gewürz', 'Petersilie – Kraut, vitaminreich'),
  ('honey', 'Honig', 'Honey', 'gruen', 'Süßungsmittel', 'Honig – natürliches Süßungsmittel'),
  ('ahornsirup', 'Ahornsirup', 'Maple Syrup', 'gruen', 'Süßungsmittel', 'Ahornsirup – natürlich, mineralstoffreich'),
  ('maple syrup', 'Ahornsirup', 'Maple Syrup', 'gruen', 'Süßungsmittel', 'Ahornsirup – natürlich, mineralstoffreich'),
  ('dattelsüße', 'Dattelsüße', 'Date Syrup', 'gruen', 'Süßungsmittel', 'Dattelsüße – natürlich, ballaststoffreich'),
  ('date syrup', 'Dattelsüße', 'Date Syrup', 'gruen', 'Süßungsmittel', 'Dattelsüße – natürlich, ballaststoffreich'),
  ('xylit', 'Xylit', 'Xylitol', 'gruen', 'Süßungsmittel', 'Birkenzucker – zahnfreundlich (für Hunde giftig!)'),
  ('xylitol', 'Xylit', 'Xylitol', 'gruen', 'Süßungsmittel', 'Birkenzucker – zahnfreundlich (für Hunde giftig!)'),
  ('erythrit', 'Erythrit', 'Erythritol', 'gruen', 'Süßungsmittel', 'Erythrit – kalorienfrei, gut verträglich'),
  ('erythritol', 'Erythrit', 'Erythritol', 'gruen', 'Süßungsmittel', 'Erythrit – kalorienfrei, gut verträglich'),
  ('stevia', 'Stevia', 'Steviol Glycosides', 'gruen', 'Süßungsmittel', 'Stevia – pflanzlich, kalorienfrei'),
  ('steviol glycosides', 'Stevia', 'Steviol Glycosides', 'gruen', 'Süßungsmittel', 'Stevia – pflanzlich, kalorienfrei'),
  ('oats', 'Hafer', 'Oats', 'gruen', 'Getreide', 'Hafer – ballaststoffreich, sättigend'),
  ('dinkel', 'Dinkel', 'Spelt', 'gruen', 'Getreide', 'Dinkel – Urgetreide, gut verträglich'),
  ('spelt', 'Dinkel', 'Spelt', 'gruen', 'Getreide', 'Dinkel – Urgetreide, gut verträglich'),
  ('buchweizen', 'Buchweizen', 'Buckwheat', 'gruen', 'Getreide', 'Buchweizen – glutenfrei, nährstoffreich'),
  ('buckwheat', 'Buchweizen', 'Buckwheat', 'gruen', 'Getreide', 'Buchweizen – glutenfrei, nährstoffreich'),
  ('quinoa', 'Quinoa', 'Quinoa', 'gruen', 'Getreide', 'Quinoa – proteinreich, glutenfrei'),
  ('hirse', 'Hirse', 'Millet', 'gruen', 'Getreide', 'Hirse – glutenfrei, mineralstoffreich'),
  ('millet', 'Hirse', 'Millet', 'gruen', 'Getreide', 'Hirse – glutenfrei, mineralstoffreich')
on conflict (norm_key) do update set d=excluded.d, i=excluded.i, a=excluded.a, k=excluded.k, g=excluded.g;

insert into clevia_stoffe (norm_key, d, i, a, k, g) values
  ('mandeln', 'Mandeln', 'Almonds', 'gruen', 'Nuss', 'Mandeln – proteinreich, gesunde Fette'),
  ('almonds', 'Mandeln', 'Almonds', 'gruen', 'Nuss', 'Mandeln – proteinreich, gesunde Fette'),
  ('walnüsse', 'Walnüsse', 'Walnuts', 'gruen', 'Nuss', 'Walnüsse – Omega-3-reich'),
  ('walnuts', 'Walnüsse', 'Walnuts', 'gruen', 'Nuss', 'Walnüsse – Omega-3-reich'),
  ('cashew', 'Cashew', 'Cashews', 'gruen', 'Nuss', 'Cashewkerne – cremig, mineralstoffreich'),
  ('cashews', 'Cashew', 'Cashews', 'gruen', 'Nuss', 'Cashewkerne – cremig, mineralstoffreich'),
  ('leinsamen', 'Leinsamen', 'Flaxseed', 'gruen', 'Samen', 'Leinsamen – Omega-3, ballaststoffreich'),
  ('flaxseed', 'Leinsamen', 'Flaxseed', 'gruen', 'Samen', 'Leinsamen – Omega-3, ballaststoffreich'),
  ('chiasamen', 'Chiasamen', 'Chia Seeds', 'gruen', 'Samen', 'Chiasamen – Omega-3, quellend'),
  ('chia seeds', 'Chiasamen', 'Chia Seeds', 'gruen', 'Samen', 'Chiasamen – Omega-3, quellend'),
  ('kürbiskerne', 'Kürbiskerne', 'Pumpkin Seeds', 'gruen', 'Samen', 'Kürbiskerne – zinkreich'),
  ('pumpkin seeds', 'Kürbiskerne', 'Pumpkin Seeds', 'gruen', 'Samen', 'Kürbiskerne – zinkreich'),
  ('sonnenblumenkerne', 'Sonnenblumenkerne', 'Sunflower Seeds', 'gruen', 'Samen', 'Sonnenblumenkerne – vitaminreich'),
  ('sunflower seeds', 'Sonnenblumenkerne', 'Sunflower Seeds', 'gruen', 'Samen', 'Sonnenblumenkerne – vitaminreich'),
  ('apfelessig', 'Apfelessig', 'Apple Cider Vinegar', 'gruen', 'Grundzutat', 'Apfelessig – natürlich, verdauungsfördernd'),
  ('apple cider vinegar', 'Apfelessig', 'Apple Cider Vinegar', 'gruen', 'Grundzutat', 'Apfelessig – natürlich, verdauungsfördernd'),
  ('kokosmilch', 'Kokosmilch', 'Coconut Milk', 'gruen', 'Grundzutat', 'Kokosmilch – pflanzlich, cremig'),
  ('coconut milk', 'Kokosmilch', 'Coconut Milk', 'gruen', 'Grundzutat', 'Kokosmilch – pflanzlich, cremig'),
  ('hafermilch', 'Hafermilch', 'Oat Drink', 'gruen', 'Grundzutat', 'Haferdrink – pflanzlich (auf Zusätze achten)'),
  ('oat drink', 'Hafermilch', 'Oat Drink', 'gruen', 'Grundzutat', 'Haferdrink – pflanzlich (auf Zusätze achten)'),
  ('mandelmilch', 'Mandelmilch', 'Almond Drink', 'gruen', 'Grundzutat', 'Mandeldrink – pflanzlich, leicht'),
  ('almond drink', 'Mandelmilch', 'Almond Drink', 'gruen', 'Grundzutat', 'Mandeldrink – pflanzlich, leicht'),
  ('tahini', 'Tahini', 'Tahini', 'gruen', 'Grundzutat', 'Sesammus – calciumreich'),
  ('kakao', 'Kakao', 'Cocoa', 'gruen', 'Grundzutat', 'Kakao – antioxidativ (ungesüßt)'),
  ('cocoa', 'Kakao', 'Cocoa', 'gruen', 'Grundzutat', 'Kakao – antioxidativ (ungesüßt)'),
  ('natron', 'Natron', 'Sodium Bicarbonate', 'gruen', 'Reiniger', 'Natron – mild, vielseitig, geruchsneutralisierend'),
  ('sodium bicarbonate', 'Natron', 'Sodium Bicarbonate', 'gruen', 'Reiniger', 'Natron – mild, vielseitig, geruchsneutralisierend'),
  ('soda', 'Soda', 'Sodium Carbonate', 'gruen', 'Reiniger', 'Waschsoda – fettlösend, wasserenthärtend'),
  ('sodium carbonate', 'Soda', 'Sodium Carbonate', 'gruen', 'Reiniger', 'Waschsoda – fettlösend, wasserenthärtend'),
  ('essig', 'Essig', 'Acetic Acid', 'gruen', 'Reiniger', 'Essigsäure – natürlicher Kalk- und Fettlöser'),
  ('acetic acid', 'Essig', 'Acetic Acid', 'gruen', 'Reiniger', 'Essigsäure – natürlicher Kalk- und Fettlöser'),
  ('kernseife', 'Kernseife', 'Sodium Palmate', 'gruen', 'Reiniger', 'Kernseife – pflanzenbasiert, biologisch abbaubar'),
  ('sodium palmate', 'Kernseife', 'Sodium Palmate', 'gruen', 'Reiniger', 'Kernseife – pflanzenbasiert, biologisch abbaubar'),
  ('schmierseife', 'Schmierseife', 'Potassium Oleate', 'gruen', 'Reiniger', 'Schmierseife – pflanzlich, biologisch abbaubar'),
  ('potassium oleate', 'Schmierseife', 'Potassium Oleate', 'gruen', 'Reiniger', 'Schmierseife – pflanzlich, biologisch abbaubar'),
  ('waschnuss', 'Waschnuss', 'Sapindus Mukorossi Extract', 'gruen', 'Reiniger', 'Waschnuss – natürliche Saponine'),
  ('sapindus mukorossi extract', 'Waschnuss', 'Sapindus Mukorossi Extract', 'gruen', 'Reiniger', 'Waschnuss – natürliche Saponine'),
  ('optische aufheller', 'Optische Aufheller', 'Optical Brighteners', 'rot', 'Reiniger', 'Optische Aufheller – reizend, schwer abbaubar, nur optischer Effekt'),
  ('optical brighteners', 'Optische Aufheller', 'Optical Brighteners', 'rot', 'Reiniger', 'Optische Aufheller – reizend, schwer abbaubar, nur optischer Effekt'),
  ('phosphate', 'Phosphate', 'Phosphates', 'rot', 'Reiniger', 'Phosphate – überdüngen Gewässer (Eutrophierung)'),
  ('phosphates', 'Phosphate', 'Phosphates', 'rot', 'Reiniger', 'Phosphate – überdüngen Gewässer (Eutrophierung)'),
  ('chlorbleiche', 'Chlorbleiche', 'Sodium Hypochlorite', 'rot', 'Reiniger', 'Chlorbleiche – aggressiv, bildet giftige Verbindungen'),
  ('sodium hypochlorite', 'Chlorbleiche', 'Sodium Hypochlorite', 'rot', 'Reiniger', 'Chlorbleiche – aggressiv, bildet giftige Verbindungen'),
  ('quats', 'Quats', 'Benzalkonium Chloride', 'rot', 'Reiniger', 'Quaternäre Ammoniumverbindungen – reizend, Resistenzbildung'),
  ('benzalkonium chloride', 'Quats', 'Benzalkonium Chloride', 'rot', 'Reiniger', 'Quaternäre Ammoniumverbindungen – reizend, Resistenzbildung'),
  ('methylisothiazolinon', 'Methylisothiazolinon', 'Methylisothiazolinone', 'rot', 'Konservierer', 'MI – starkes Kontaktallergen'),
  ('methylisothiazolinone', 'Methylisothiazolinon', 'Methylisothiazolinone', 'rot', 'Konservierer', 'MI – starkes Kontaktallergen'),
  ('haferflocken', 'Haferflocken', 'Oat Flakes', 'gruen', 'Getreide', 'Haferflocken – ballaststoffreich, sättigend'),
  ('oat flakes', 'Haferflocken', 'Oat Flakes', 'gruen', 'Getreide', 'Haferflocken – ballaststoffreich, sättigend'),
  ('dinkelflocken', 'Dinkelflocken', 'Spelt Flakes', 'gruen', 'Getreide', 'Dinkelflocken – Urgetreide, gut verträglich')
on conflict (norm_key) do update set d=excluded.d, i=excluded.i, a=excluded.a, k=excluded.k, g=excluded.g;

insert into clevia_stoffe (norm_key, d, i, a, k, g) values
  ('spelt flakes', 'Dinkelflocken', 'Spelt Flakes', 'gruen', 'Getreide', 'Dinkelflocken – Urgetreide, gut verträglich'),
  ('reisflocken', 'Reisflocken', 'Rice Flakes', 'gelb', 'Getreide', 'Reisflocken – glutenfrei (Arsen aus Anbau beachten)'),
  ('rice flakes', 'Reisflocken', 'Rice Flakes', 'gelb', 'Getreide', 'Reisflocken – glutenfrei (Arsen aus Anbau beachten)'),
  ('pektin', 'Pektin', 'Pectin', 'gruen', 'Verdicker', 'Pektin – aus Früchten, Geliermittel (E440)'),
  ('pectin', 'Pektin', 'Pectin', 'gruen', 'Verdicker', 'Pektin – aus Früchten, Geliermittel (E440)'),
  ('agar', 'Agar', 'Agar', 'gruen', 'Verdicker', 'Agar-Agar – pflanzliches Geliermittel aus Algen'),
  ('carrageen', 'Carrageen', 'Carrageenan', 'gelb', 'Verdicker', 'Carrageen – aus Algen, aber Verdauungsreizung möglich (E407)'),
  ('carrageenan', 'Carrageen', 'Carrageenan', 'gelb', 'Verdicker', 'Carrageen – aus Algen, aber Verdauungsreizung möglich (E407)'),
  ('sonnenblumenlecithin', 'Sonnenblumenlecithin', 'Helianthus Annuus Lecithin', 'gruen', 'Emulgator', 'Sonnenblumenlecithin – natürlicher Emulgator'),
  ('helianthus annuus lecithin', 'Sonnenblumenlecithin', 'Helianthus Annuus Lecithin', 'gruen', 'Emulgator', 'Sonnenblumenlecithin – natürlicher Emulgator'),
  ('sojalecithin', 'Sojalecithin', 'Lecithin', 'gruen', 'Emulgator', 'Lecithin – natürlicher Emulgator (E322)'),
  ('lecithin', 'Sojalecithin', 'Lecithin', 'gruen', 'Emulgator', 'Lecithin – natürlicher Emulgator (E322)'),
  ('magermilch', 'Magermilch', 'Skimmed Milk', 'gruen', 'Grundzutat', 'Magermilch – proteinreich'),
  ('skimmed milk', 'Magermilch', 'Skimmed Milk', 'gruen', 'Grundzutat', 'Magermilch – proteinreich'),
  ('molkenprotein', 'Molkenprotein', 'Whey Protein', 'gruen', 'Protein', 'Molkenprotein – hochwertiges Eiweiß'),
  ('whey protein', 'Molkenprotein', 'Whey Protein', 'gruen', 'Protein', 'Molkenprotein – hochwertiges Eiweiß'),
  ('erbsenprotein', 'Erbsenprotein', 'Pea Protein', 'gruen', 'Protein', 'Erbsenprotein – pflanzlich, gut verträglich'),
  ('pea protein', 'Erbsenprotein', 'Pea Protein', 'gruen', 'Protein', 'Erbsenprotein – pflanzlich, gut verträglich'),
  ('reisprotein', 'Reisprotein', 'Rice Protein', 'gelb', 'Protein', 'Reisprotein – pflanzlich (Schwermetall-Rückstände möglich)'),
  ('rice protein', 'Reisprotein', 'Rice Protein', 'gelb', 'Protein', 'Reisprotein – pflanzlich (Schwermetall-Rückstände möglich)'),
  ('butter', 'Butter', 'Butter', 'gruen', 'Fett', 'Butter – natürliches Fett, in Maßen'),
  ('ghee', 'Ghee', 'Ghee', 'gruen', 'Fett', 'Ghee – geklärte Butter, hoch erhitzbar'),
  ('sheanussbutter', 'Sheanussbutter', 'Butyrospermum Parkii Butter', 'gruen', 'Pflanzenbutter', 'Sheabutter – reichhaltig, schützend'),
  ('kokosnussöl', 'Kokosnussöl', 'Cocos Nucifera Oil', 'gruen', 'Pflanzenöl', 'Kokosöl – pflegend, leicht antimikrobiell'),
  ('milchsäurebakterien', 'Milchsäurebakterien', 'Lactobacillus', 'gruen', 'Wirkstoff', 'Milchsäurebakterien – hautfreundlich, Mikrobiom'),
  ('lactobacillus', 'Milchsäurebakterien', 'Lactobacillus', 'gruen', 'Wirkstoff', 'Milchsäurebakterien – hautfreundlich, Mikrobiom'),
  ('kieselerde', 'Kieselerde', 'Silica', 'gruen', 'Mineral', 'Kieselerde – mattierend, mineralisch'),
  ('silica', 'Kieselerde', 'Silica', 'gruen', 'Mineral', 'Kieselerde – mattierend, mineralisch'),
  ('heilerde', 'Heilerde', 'Clay', 'gruen', 'Mineral', 'Heilerde – klärend, entgiftend'),
  ('clay', 'Heilerde', 'Clay', 'gruen', 'Mineral', 'Heilerde – klärend, entgiftend'),
  ('tonerde', 'Tonerde', 'Kaolin', 'gruen', 'Mineral', 'Weiße Tonerde – sanft reinigend'),
  ('kaolin', 'Tonerde', 'Kaolin', 'gruen', 'Mineral', 'Weiße Tonerde – sanft reinigend'),
  ('zinkoxid', 'Zinkoxid', 'Zinc Oxide', 'gruen', 'Mineral', 'Zinkoxid – mineralischer UV-Schutz, bei Hautreizung'),
  ('zinc oxide', 'Zinkoxid', 'Zinc Oxide', 'gruen', 'Mineral', 'Zinkoxid – mineralischer UV-Schutz, bei Hautreizung'),
  ('pentylenglykol', 'Pentylenglykol', 'Pentylene Glycol', 'gruen', 'Konservierer', 'Pentylenglykol – mild, oft in Naturkosmetik'),
  ('pentylene glycol', 'Pentylenglykol', 'Pentylene Glycol', 'gruen', 'Konservierer', 'Pentylenglykol – mild, oft in Naturkosmetik'),
  ('ammoniumlaurylsulfat', 'Ammoniumlaurylsulfat', 'Ammonium Lauryl Sulfate', 'gelb', 'Tensid', 'ALS – reizendes Sulfat-Tensid'),
  ('ammonium lauryl sulfate', 'Ammoniumlaurylsulfat', 'Ammonium Lauryl Sulfate', 'gelb', 'Tensid', 'ALS – reizendes Sulfat-Tensid'),
  ('natriumcocoylisethionat', 'Natriumcocoylisethionat', 'Sodium Cocoyl Isethionate', 'gruen', 'Tensid', 'Mildes Kokos-Tensid, hautfreundlich'),
  ('sodium cocoyl isethionate', 'Natriumcocoylisethionat', 'Sodium Cocoyl Isethionate', 'gruen', 'Tensid', 'Mildes Kokos-Tensid, hautfreundlich'),
  ('coco glucosid', 'Coco-Glucosid', 'Coco-Glucoside', 'gruen', 'Tensid', 'Zuckertensid aus Kokos – sehr mild, abbaubar'),
  ('decyl glucosid', 'Decyl-Glucosid', 'Decyl Glucoside', 'gruen', 'Tensid', 'Zuckertensid – sehr mild'),
  ('natriumcocoylglutamat', 'Natriumcocoylglutamat', 'Sodium Cocoyl Glutamate', 'gruen', 'Tensid', 'Aminosäure-Tensid – sehr mild'),
  ('sodium cocoyl glutamate', 'Natriumcocoylglutamat', 'Sodium Cocoyl Glutamate', 'gruen', 'Tensid', 'Aminosäure-Tensid – sehr mild'),
  ('disodium laureth sulfosuccinate', 'Disodium Laureth Sulfosuccinate', 'Disodium Laureth Sulfosuccinate', 'gruen', 'Tensid', 'Mildes Tensid, oft in Baby-Produkten'),
  ('natriumlauroylsarcosinat', 'Natriumlauroylsarcosinat', 'Sodium Lauroyl Sarcosinate', 'gruen', 'Tensid', 'Mildes Aminosäure-Tensid'),
  ('sodium lauroyl sarcosinate', 'Natriumlauroylsarcosinat', 'Sodium Lauroyl Sarcosinate', 'gruen', 'Tensid', 'Mildes Aminosäure-Tensid'),
  ('dimethicon', 'Dimethicon', 'Dimethicone', 'gelb', 'Silikon', 'Silikon – legt Film auf Haut/Haar, schwer abbaubar'),
  ('dimethicone', 'Dimethicon', 'Dimethicone', 'gelb', 'Silikon', 'Silikon – legt Film auf Haut/Haar, schwer abbaubar'),
  ('cyclopentasiloxan', 'Cyclopentasiloxan', 'Cyclopentasiloxane', 'rot', 'Silikon', 'Flüchtiges Silikon – umweltbedenklich (PBT-Verdacht)')
on conflict (norm_key) do update set d=excluded.d, i=excluded.i, a=excluded.a, k=excluded.k, g=excluded.g;

insert into clevia_stoffe (norm_key, d, i, a, k, g) values
  ('cyclopentasiloxane', 'Cyclopentasiloxan', 'Cyclopentasiloxane', 'rot', 'Silikon', 'Flüchtiges Silikon – umweltbedenklich (PBT-Verdacht)'),
  ('cyclohexasiloxan', 'Cyclohexasiloxan', 'Cyclohexasiloxane', 'rot', 'Silikon', 'Flüchtiges Silikon – umweltproblematisch'),
  ('cyclohexasiloxane', 'Cyclohexasiloxan', 'Cyclohexasiloxane', 'rot', 'Silikon', 'Flüchtiges Silikon – umweltproblematisch'),
  ('amodimethicon', 'Amodimethicon', 'Amodimethicone', 'gelb', 'Silikon', 'Silikon – Filmbildner in Haarpflege'),
  ('amodimethicone', 'Amodimethicon', 'Amodimethicone', 'gelb', 'Silikon', 'Silikon – Filmbildner in Haarpflege'),
  ('dimethiconol', 'Dimethiconol', 'Dimethiconol', 'gelb', 'Silikon', 'Silikon – schwer abbaubar'),
  ('phenyl trimethicone', 'Phenyl Trimethicone', 'Phenyl Trimethicone', 'gelb', 'Silikon', 'Silikon – glättender Filmbildner'),
  ('trisiloxan', 'Trisiloxan', 'Trisiloxane', 'gelb', 'Silikon', 'Silikon – leicht, aber schwer abbaubar'),
  ('trisiloxane', 'Trisiloxan', 'Trisiloxane', 'gelb', 'Silikon', 'Silikon – leicht, aber schwer abbaubar'),
  ('glycerylstearat', 'Glycerylstearat', 'Glyceryl Stearate', 'gruen', 'Emulgator', 'Emulgator auf Fettsäurebasis – unbedenklich'),
  ('glyceryl stearate', 'Glycerylstearat', 'Glyceryl Stearate', 'gruen', 'Emulgator', 'Emulgator auf Fettsäurebasis – unbedenklich'),
  ('ceteareth 20', 'Ceteareth-20', 'Ceteareth-20', 'gelb', 'Emulgator', 'PEG-Emulgator – Dioxan-Verunreinigung möglich'),
  ('ceteareth 25', 'Ceteareth-25', 'Ceteareth-25', 'gelb', 'Emulgator', 'PEG-Emulgator – ethoxyliert'),
  ('polysorbat 20', 'Polysorbat 20', 'Polysorbate 20', 'gelb', 'Emulgator', 'Ethoxylierter Emulgator (PEG-artig)'),
  ('polysorbate 20', 'Polysorbat 20', 'Polysorbate 20', 'gelb', 'Emulgator', 'Ethoxylierter Emulgator (PEG-artig)'),
  ('polysorbat 60', 'Polysorbat 60', 'Polysorbate 60', 'gelb', 'Emulgator', 'Ethoxylierter Emulgator'),
  ('polysorbate 60', 'Polysorbat 60', 'Polysorbate 60', 'gelb', 'Emulgator', 'Ethoxylierter Emulgator'),
  ('polysorbat 80', 'Polysorbat 80', 'Polysorbate 80', 'gelb', 'Emulgator', 'Ethoxylierter Emulgator'),
  ('polysorbate 80', 'Polysorbat 80', 'Polysorbate 80', 'gelb', 'Emulgator', 'Ethoxylierter Emulgator'),
  ('peg 100 stearat', 'PEG-100 Stearat', 'PEG-100 Stearate', 'gelb', 'Emulgator', 'PEG-Emulgator – Dioxan-Verunreinigung möglich'),
  ('peg 100 stearate', 'PEG-100 Stearat', 'PEG-100 Stearate', 'gelb', 'Emulgator', 'PEG-Emulgator – Dioxan-Verunreinigung möglich'),
  ('peg 40 hydriertes rizinusöl', 'PEG-40 Hydriertes Rizinusöl', 'PEG-40 Hydrogenated Castor Oil', 'gelb', 'Emulgator', 'PEG-Löslichkeitsvermittler'),
  ('peg 40 hydrogenated castor oil', 'PEG-40 Hydriertes Rizinusöl', 'PEG-40 Hydrogenated Castor Oil', 'gelb', 'Emulgator', 'PEG-Löslichkeitsvermittler'),
  ('cetylstearylsulfat', 'Cetylstearylsulfat', 'Sodium Cetearyl Sulfate', 'gelb', 'Emulgator', 'Sulfat-Emulgator'),
  ('sodium cetearyl sulfate', 'Cetylstearylsulfat', 'Sodium Cetearyl Sulfate', 'gelb', 'Emulgator', 'Sulfat-Emulgator'),
  ('glyceryl stearate citrate', 'Glyceryl Stearate Citrate', 'Glyceryl Stearate Citrate', 'gruen', 'Emulgator', 'Milder Emulgator, oft in Naturkosmetik'),
  ('cetearyl glucoside', 'Cetearyl Glucoside', 'Cetearyl Glucoside', 'gruen', 'Emulgator', 'Zucker-Emulgator, Naturkosmetik-geeignet'),
  ('sorbitan olivate', 'Sorbitan Olivate', 'Sorbitan Olivate', 'gruen', 'Emulgator', 'Olivenöl-Emulgator (Olivem), naturkosmetiktauglich'),
  ('propylenglykol', 'Propylenglykol', 'Propylene Glycol', 'gelb', 'Feuchthaltemittel', 'Synthetisches Feuchthaltemittel – kann reizen'),
  ('propylene glycol', 'Propylenglykol', 'Propylene Glycol', 'gelb', 'Feuchthaltemittel', 'Synthetisches Feuchthaltemittel – kann reizen'),
  ('butylenglykol', 'Butylenglykol', 'Butylene Glycol', 'gelb', 'Feuchthaltemittel', 'Synthetisches Feuchthaltemittel'),
  ('butylene glycol', 'Butylenglykol', 'Butylene Glycol', 'gelb', 'Feuchthaltemittel', 'Synthetisches Feuchthaltemittel'),
  ('propandiol', 'Propandiol', 'Propanediol', 'gruen', 'Feuchthaltemittel', 'Pflanzliches Feuchthaltemittel (aus Mais)'),
  ('propanediol', 'Propandiol', 'Propanediol', 'gruen', 'Feuchthaltemittel', 'Pflanzliches Feuchthaltemittel (aus Mais)'),
  ('caprylyl glycol', 'Caprylyl Glycol', 'Caprylyl Glycol', 'gruen', 'Feuchthaltemittel', 'Mild, oft in Naturkosmetik'),
  ('dipropylenglykol', 'Dipropylenglykol', 'Dipropylene Glycol', 'gelb', 'Feuchthaltemittel', 'Synthetisches Lösungsmittel'),
  ('dipropylene glycol', 'Dipropylenglykol', 'Dipropylene Glycol', 'gelb', 'Feuchthaltemittel', 'Synthetisches Lösungsmittel'),
  ('acrylate copolymer', 'Acrylate Copolymer', 'Acrylates Copolymer', 'rot', 'Filmbildner', 'Synthetisches Polymer – Mikroplastik, schwer abbaubar'),
  ('acrylates copolymer', 'Acrylate Copolymer', 'Acrylates Copolymer', 'rot', 'Filmbildner', 'Synthetisches Polymer – Mikroplastik, schwer abbaubar'),
  ('acrylates/c10 30 alkyl acrylate crosspolymer', 'Acrylates/C10-30 Alkyl Acrylate Crosspolymer', 'Acrylates/C10-30 Alkyl Acrylate Crosspolymer', 'gelb', 'Filmbildner', 'Verdickungspolymer – synthetisch'),
  ('carbomer', 'Carbomer', 'Carbomer', 'gelb', 'Verdicker', 'Synthetisches Verdickungsmittel'),
  ('polyquaternium 7', 'Polyquaternium-7', 'Polyquaternium-7', 'gelb', 'Filmbildner', 'Synthetisches Konditionierpolymer'),
  ('vp/va copolymer', 'VP/VA Copolymer', 'VP/VA Copolymer', 'gelb', 'Filmbildner', 'Synthetisches Styling-Polymer'),
  ('polyethylen', 'Polyethylen', 'Polyethylene', 'rot', 'Filmbildner', 'Mikroplastik – in Peelings und Cremes bedenklich'),
  ('polyethylene', 'Polyethylen', 'Polyethylene', 'rot', 'Filmbildner', 'Mikroplastik – in Peelings und Cremes bedenklich'),
  ('nylon 12', 'Nylon-12', 'Nylon-12', 'rot', 'Filmbildner', 'Mikroplastik-Pulver in Make-up'),
  ('pvp', 'PVP', 'PVP', 'gelb', 'Filmbildner', 'Synthetisches Styling-Polymer'),
  ('butylparaben', 'Butylparaben', 'Butylparaben', 'rot', 'Konservierer', 'Paraben – hormonell wirksam (Verdacht)'),
  ('methylchloroisothiazolinon', 'Methylchloroisothiazolinon', 'Methylchloroisothiazolinone', 'rot', 'Konservierer', 'MCI – starkes Allergen'),
  ('methylchloroisothiazolinone', 'Methylchloroisothiazolinon', 'Methylchloroisothiazolinone', 'rot', 'Konservierer', 'MCI – starkes Allergen')
on conflict (norm_key) do update set d=excluded.d, i=excluded.i, a=excluded.a, k=excluded.k, g=excluded.g;

insert into clevia_stoffe (norm_key, d, i, a, k, g) values
  ('dehydroacetic acid', 'Dehydroacetic Acid', 'Dehydroacetic Acid', 'gruen', 'Konservierer', 'Milder Konservierer, naturkosmetiktauglich'),
  ('natriumhydroxymethylglycinat', 'Natriumhydroxymethylglycinat', 'Sodium Hydroxymethylglycinate', 'gelb', 'Konservierer', 'Formaldehyd-Abspalter (Verdacht)'),
  ('sodium hydroxymethylglycinate', 'Natriumhydroxymethylglycinat', 'Sodium Hydroxymethylglycinate', 'gelb', 'Konservierer', 'Formaldehyd-Abspalter (Verdacht)'),
  ('dmdm hydantoin', 'DMDM Hydantoin', 'DMDM Hydantoin', 'rot', 'Konservierer', 'Formaldehyd-Abspalter – bedenklich'),
  ('imidazolidinyl urea', 'Imidazolidinyl Urea', 'Imidazolidinyl Urea', 'rot', 'Konservierer', 'Formaldehyd-Abspalter'),
  ('triclosan', 'Triclosan', 'Triclosan', 'rot', 'Konservierer', 'Antibakteriell – hormonell wirksam, Resistenzen'),
  ('octocrylen', 'Octocrylen', 'Octocrylene', 'rot', 'UV-Filter', 'Chemischer UV-Filter – Allergen, Umweltbelastung'),
  ('octocrylene', 'Octocrylen', 'Octocrylene', 'rot', 'UV-Filter', 'Chemischer UV-Filter – Allergen, Umweltbelastung'),
  ('ethylhexyl methoxycinnamat', 'Ethylhexyl Methoxycinnamat', 'Ethylhexyl Methoxycinnamate', 'rot', 'UV-Filter', 'Octinoxat – hormonell wirksam (Verdacht), korallenschädlich'),
  ('ethylhexyl methoxycinnamate', 'Ethylhexyl Methoxycinnamat', 'Ethylhexyl Methoxycinnamate', 'rot', 'UV-Filter', 'Octinoxat – hormonell wirksam (Verdacht), korallenschädlich'),
  ('oxybenzon', 'Oxybenzon', 'Benzophenone-3', 'rot', 'UV-Filter', 'Hormonell wirksam, korallenschädlich'),
  ('benzophenone 3', 'Oxybenzon', 'Benzophenone-3', 'rot', 'UV-Filter', 'Hormonell wirksam, korallenschädlich'),
  ('homosalat', 'Homosalat', 'Homosalate', 'gelb', 'UV-Filter', 'Chemischer UV-Filter – hormonelle Wirkung diskutiert'),
  ('homosalate', 'Homosalat', 'Homosalate', 'gelb', 'UV-Filter', 'Chemischer UV-Filter – hormonelle Wirkung diskutiert'),
  ('avobenzon', 'Avobenzon', 'Butyl Methoxydibenzoylmethane', 'gelb', 'UV-Filter', 'Chemischer UV-Filter – instabil, kann reizen'),
  ('butyl methoxydibenzoylmethane', 'Avobenzon', 'Butyl Methoxydibenzoylmethane', 'gelb', 'UV-Filter', 'Chemischer UV-Filter – instabil, kann reizen'),
  ('titandioxid', 'Titandioxid', 'Titanium Dioxide', 'gruen', 'UV-Filter', 'Mineralischer UV-Filter – sicher (nicht als Spray/Puder einatmen)'),
  ('titanium dioxide', 'Titandioxid', 'Titanium Dioxide', 'gruen', 'UV-Filter', 'Mineralischer UV-Filter – sicher (nicht als Spray/Puder einatmen)'),
  ('limonen', 'Limonen', 'Limonene', 'gelb', 'Duftstoff', 'Natürliches Duft-Allergen (aus Zitrus)'),
  ('limonene', 'Limonen', 'Limonene', 'gelb', 'Duftstoff', 'Natürliches Duft-Allergen (aus Zitrus)'),
  ('linalool', 'Linalool', 'Linalool', 'gelb', 'Duftstoff', 'Natürliches Duft-Allergen'),
  ('citronellol', 'Citronellol', 'Citronellol', 'gelb', 'Duftstoff', 'Duft-Allergen'),
  ('geraniol', 'Geraniol', 'Geraniol', 'gelb', 'Duftstoff', 'Duft-Allergen'),
  ('cumarin', 'Cumarin', 'Coumarin', 'gelb', 'Duftstoff', 'Duft-Allergen (Tonkabohne/Zimt)'),
  ('coumarin', 'Cumarin', 'Coumarin', 'gelb', 'Duftstoff', 'Duft-Allergen (Tonkabohne/Zimt)'),
  ('eugenol', 'Eugenol', 'Eugenol', 'gelb', 'Duftstoff', 'Duft-Allergen (Nelke)'),
  ('citral', 'Citral', 'Citral', 'gelb', 'Duftstoff', 'Duft-Allergen (Zitrus)'),
  ('benzyl salicylate', 'Benzyl Salicylate', 'Benzyl Salicylate', 'gelb', 'Duftstoff', 'Duft-Allergen'),
  ('hexyl cinnamal', 'Hexyl Cinnamal', 'Hexyl Cinnamal', 'gelb', 'Duftstoff', 'Duft-Allergen'),
  ('talkum', 'Talkum', 'Talc', 'gelb', 'Füllstoff', 'Mineralpulver – asbestfrei-Zertifizierung wichtig'),
  ('talc', 'Talkum', 'Talc', 'gelb', 'Füllstoff', 'Mineralpulver – asbestfrei-Zertifizierung wichtig'),
  ('mica', 'Mica', 'Mica', 'gruen', 'Farbgeber', 'Mineralisches Glanzpigment'),
  ('eisenoxide', 'Eisenoxide', 'Iron Oxides', 'gruen', 'Farbgeber', 'Mineralische Farbpigmente – unbedenklich'),
  ('iron oxides', 'Eisenoxide', 'Iron Oxides', 'gruen', 'Farbgeber', 'Mineralische Farbpigmente – unbedenklich'),
  ('titandioxid ci 77891', 'Titandioxid CI 77891', 'CI 77891', 'gruen', 'Farbgeber', 'Weißpigment – mineralisch'),
  ('ci 77891', 'Titandioxid CI 77891', 'CI 77891', 'gruen', 'Farbgeber', 'Weißpigment – mineralisch'),
  ('salicylsäure', 'Salicylsäure', 'Salicylic Acid', 'gelb', 'Wirkstoff', 'BHA-Peeling – wirksam, in Schwangerschaft meiden'),
  ('salicylic acid', 'Salicylsäure', 'Salicylic Acid', 'gelb', 'Wirkstoff', 'BHA-Peeling – wirksam, in Schwangerschaft meiden'),
  ('retinol', 'Retinol', 'Retinol', 'gelb', 'Wirkstoff', 'Vitamin A – Anti-Aging, in Schwangerschaft meiden'),
  ('fruktosesirup', 'Fruktosesirup', 'Fructose Syrup', 'rot', 'Süßungsmittel', 'Fruchtzuckersirup – belastet Leber, meiden'),
  ('fructose syrup', 'Fruktosesirup', 'Fructose Syrup', 'rot', 'Süßungsmittel', 'Fruchtzuckersirup – belastet Leber, meiden'),
  ('glukose fruktose sirup', 'Glukose-Fruktose-Sirup', 'Glucose-Fructose Syrup', 'rot', 'Süßungsmittel', 'Isoglukose – stark verarbeitet, meiden'),
  ('glucose fructose syrup', 'Glukose-Fruktose-Sirup', 'Glucose-Fructose Syrup', 'rot', 'Süßungsmittel', 'Isoglukose – stark verarbeitet, meiden'),
  ('maltodextrin', 'Maltodextrin', 'Maltodextrin', 'gelb', 'Süßungsmittel', 'Stärkeabbauprodukt – hoher glykämischer Index'),
  ('aspartam', 'Aspartam', 'Aspartame', 'rot', 'Süßstoff', 'Süßstoff (E951) – umstritten (IARC: möglicherweise krebserregend)'),
  ('aspartame', 'Aspartam', 'Aspartame', 'rot', 'Süßstoff', 'Süßstoff (E951) – umstritten (IARC: möglicherweise krebserregend)'),
  ('sucralose', 'Sucralose', 'Sucralose', 'gelb', 'Süßstoff', 'Süßstoff (E955) – Darmflora-Effekte diskutiert'),
  ('acesulfam k', 'Acesulfam K', 'Acesulfame K', 'gelb', 'Süßstoff', 'Süßstoff (E950) – umstritten'),
  ('acesulfame k', 'Acesulfam K', 'Acesulfame K', 'gelb', 'Süßstoff', 'Süßstoff (E950) – umstritten'),
  ('saccharin', 'Saccharin', 'Saccharin', 'gelb', 'Süßstoff', 'Süßstoff (E954) – umstritten')
on conflict (norm_key) do update set d=excluded.d, i=excluded.i, a=excluded.a, k=excluded.k, g=excluded.g;

insert into clevia_stoffe (norm_key, d, i, a, k, g) values
  ('sorbit', 'Sorbit', 'Sorbitol', 'gelb', 'Süßstoff', 'Zuckeralkohol (E420) – abführend in Mengen'),
  ('sorbitol', 'Sorbit', 'Sorbitol', 'gelb', 'Süßstoff', 'Zuckeralkohol (E420) – abführend in Mengen'),
  ('maltit', 'Maltit', 'Maltitol', 'gelb', 'Süßstoff', 'Zuckeralkohol (E965) – abführend in Mengen'),
  ('maltitol', 'Maltit', 'Maltitol', 'gelb', 'Süßstoff', 'Zuckeralkohol (E965) – abführend in Mengen'),
  ('natriumnitrit', 'Natriumnitrit', 'Sodium Nitrite', 'rot', 'Konservierer', 'Pökelsalz (E250) – bildet Nitrosamine (krebserregend)'),
  ('sodium nitrite', 'Natriumnitrit', 'Sodium Nitrite', 'rot', 'Konservierer', 'Pökelsalz (E250) – bildet Nitrosamine (krebserregend)'),
  ('schwefeldioxid', 'Schwefeldioxid', 'Sulfur Dioxide', 'gelb', 'Konservierer', 'Konservierer (E220) – bei Trockenobst/Wein, Allergiker'),
  ('sulfur dioxide', 'Schwefeldioxid', 'Sulfur Dioxide', 'gelb', 'Konservierer', 'Konservierer (E220) – bei Trockenobst/Wein, Allergiker'),
  ('essigsäure', 'Essigsäure', 'Acetic Acid', 'gruen', 'Säuerungsmittel', 'Essigsäure (E260) – natürlich, unbedenklich'),
  ('apfelsäure', 'Apfelsäure', 'Malic Acid', 'gruen', 'Säuerungsmittel', 'Fruchtsäure (E296) – natürlich'),
  ('malic acid', 'Apfelsäure', 'Malic Acid', 'gruen', 'Säuerungsmittel', 'Fruchtsäure (E296) – natürlich'),
  ('ascorbinsäure', 'Ascorbinsäure', 'Ascorbic Acid', 'gruen', 'Antioxidans', 'Vitamin C (E300) – natürlich, gesund'),
  ('mononatriumglutamat', 'Mononatriumglutamat', 'Monosodium Glutamate', 'rot', 'Geschmacksverstärker', 'MSG (E621) – Geschmacksverstärker, umstritten'),
  ('monosodium glutamate', 'Mononatriumglutamat', 'Monosodium Glutamate', 'rot', 'Geschmacksverstärker', 'MSG (E621) – Geschmacksverstärker, umstritten'),
  ('vanillin', 'Vanillin', 'Vanillin', 'gelb', 'Aroma', 'Synthetischer Vanille-Ersatz'),
  ('sunflower lecithin', 'Sonnenblumenlecithin', 'Sunflower Lecithin', 'gruen', 'Emulgator', 'Natürlicher Emulgator (E322)'),
  ('soy lecithin', 'Sojalecithin', 'Soy Lecithin', 'gruen', 'Emulgator', 'Emulgator (E322) – meist unbedenklich'),
  ('mono und diglyceride', 'Mono- und Diglyceride', 'Mono- and Diglycerides', 'gelb', 'Emulgator', 'Emulgator (E471) – verarbeitet, oft aus Palmöl'),
  ('mono and diglycerides', 'Mono- und Diglyceride', 'Mono- and Diglycerides', 'gelb', 'Emulgator', 'Emulgator (E471) – verarbeitet, oft aus Palmöl'),
  ('palmfett', 'Palmfett', 'Palm Fat', 'gelb', 'Fett', 'Palmfett – ökologisch bedenklich, oft gehärtet'),
  ('palm fat', 'Palmfett', 'Palm Fat', 'gelb', 'Fett', 'Palmfett – ökologisch bedenklich, oft gehärtet'),
  ('gehärtetes fett', 'Gehärtetes Fett', 'Hydrogenated Fat', 'rot', 'Fett', 'Gehärtetes Fett – kann Transfette enthalten'),
  ('hydrogenated fat', 'Gehärtetes Fett', 'Hydrogenated Fat', 'rot', 'Fett', 'Gehärtetes Fett – kann Transfette enthalten'),
  ('karamell', 'Karamell', 'Caramel Colour', 'gelb', 'Farbstoff', 'Zuckerkulör (E150) – Variante E150d umstritten'),
  ('caramel colour', 'Karamell', 'Caramel Colour', 'gelb', 'Farbstoff', 'Zuckerkulör (E150) – Variante E150d umstritten'),
  ('kurkumin', 'Kurkumin', 'Curcumin', 'gruen', 'Farbstoff', 'Natürlicher Farbstoff aus Kurkuma (E100)'),
  ('curcumin', 'Kurkumin', 'Curcumin', 'gruen', 'Farbstoff', 'Natürlicher Farbstoff aus Kurkuma (E100)'),
  ('beta carotin', 'Beta-Carotin', 'Beta-Carotene', 'gruen', 'Farbstoff', 'Natürlicher Farbstoff/Provitamin A (E160a)'),
  ('beta carotene', 'Beta-Carotin', 'Beta-Carotene', 'gruen', 'Farbstoff', 'Natürlicher Farbstoff/Provitamin A (E160a)'),
  ('tartrazin', 'Tartrazin', 'Tartrazine', 'rot', 'Farbstoff', 'Azofarbstoff (E102) – Hyperaktivität bei Kindern (Warnhinweis)'),
  ('tartrazine', 'Tartrazin', 'Tartrazine', 'rot', 'Farbstoff', 'Azofarbstoff (E102) – Hyperaktivität bei Kindern (Warnhinweis)'),
  ('titandioxid lebensmittel', 'Titandioxid Lebensmittel', 'Titanium Dioxide E171', 'rot', 'Farbstoff', 'E171 – in EU als Lebensmittel verboten (Genotoxizität)'),
  ('titanium dioxide e171', 'Titandioxid Lebensmittel', 'Titanium Dioxide E171', 'rot', 'Farbstoff', 'E171 – in EU als Lebensmittel verboten (Genotoxizität)'),
  ('tenside', 'Tenside', 'Surfactants', 'gelb', 'Reiniger', 'Waschaktive Substanzen – auf pflanzliche Basis achten'),
  ('surfactants', 'Tenside', 'Surfactants', 'gelb', 'Reiniger', 'Waschaktive Substanzen – auf pflanzliche Basis achten'),
  ('anionische tenside', 'Anionische Tenside', 'Anionic Surfactants', 'gelb', 'Reiniger', 'Waschaktive Stoffe – Herkunft entscheidend'),
  ('anionic surfactants', 'Anionische Tenside', 'Anionic Surfactants', 'gelb', 'Reiniger', 'Waschaktive Stoffe – Herkunft entscheidend'),
  ('nichtionische tenside', 'Nichtionische Tenside', 'Non-ionic Surfactants', 'gelb', 'Reiniger', 'Waschaktive Stoffe – oft aus Erdöl'),
  ('non ionic surfactants', 'Nichtionische Tenside', 'Non-ionic Surfactants', 'gelb', 'Reiniger', 'Waschaktive Stoffe – oft aus Erdöl'),
  ('natriumcarbonat', 'Natriumcarbonat', 'Sodium Carbonate', 'gruen', 'Reiniger', 'Waschsoda – mineralisch, enthärtet Wasser'),
  ('natriumpercarbonat', 'Natriumpercarbonat', 'Sodium Percarbonate', 'gruen', 'Reiniger', 'Sauerstoffbleiche – abbaubar, milder als Chlor'),
  ('sodium percarbonate', 'Natriumpercarbonat', 'Sodium Percarbonate', 'gruen', 'Reiniger', 'Sauerstoffbleiche – abbaubar, milder als Chlor'),
  ('natriumcitrat', 'Natriumcitrat', 'Sodium Citrate', 'gruen', 'Reiniger', 'Enthärter auf Zitronensäurebasis – abbaubar'),
  ('sodium citrate', 'Natriumcitrat', 'Sodium Citrate', 'gruen', 'Reiniger', 'Enthärter auf Zitronensäurebasis – abbaubar'),
  ('chlor', 'Chlor', 'Chlorine', 'rot', 'Reiniger', 'Chlor – aggressiv, bildet giftige Nebenprodukte'),
  ('chlorine', 'Chlor', 'Chlorine', 'rot', 'Reiniger', 'Chlor – aggressiv, bildet giftige Nebenprodukte'),
  ('natriumhypochlorit', 'Natriumhypochlorit', 'Sodium Hypochlorite', 'rot', 'Reiniger', 'Chlorbleiche – reizend, umweltschädlich'),
  ('ammoniak', 'Ammoniak', 'Ammonia', 'rot', 'Reiniger', 'Aggressiv, reizt Atemwege stark'),
  ('ammonia', 'Ammoniak', 'Ammonia', 'rot', 'Reiniger', 'Aggressiv, reizt Atemwege stark'),
  ('phosphonate', 'Phosphonate', 'Phosphonates', 'gelb', 'Reiniger', 'Enthärter – schwer abbaubar')
on conflict (norm_key) do update set d=excluded.d, i=excluded.i, a=excluded.a, k=excluded.k, g=excluded.g;

insert into clevia_stoffe (norm_key, d, i, a, k, g) values
  ('phosphonates', 'Phosphonate', 'Phosphonates', 'gelb', 'Reiniger', 'Enthärter – schwer abbaubar'),
  ('zeolithe', 'Zeolithe', 'Zeolites', 'gruen', 'Reiniger', 'Mineralischer Wasserenthärter – abbaubar'),
  ('zeolites', 'Zeolithe', 'Zeolites', 'gruen', 'Reiniger', 'Mineralischer Wasserenthärter – abbaubar'),
  ('enzyme', 'Enzyme', 'Enzymes', 'gruen', 'Reiniger', 'Biologische Fleckenlöser – abbaubar (Allergiker: einatmen meiden)'),
  ('enzymes', 'Enzyme', 'Enzymes', 'gruen', 'Reiniger', 'Biologische Fleckenlöser – abbaubar (Allergiker: einatmen meiden)'),
  ('benzisothiazolinon', 'Benzisothiazolinon', 'Benzisothiazolinone', 'rot', 'Reiniger', 'Konservierer – Allergen'),
  ('benzisothiazolinone', 'Benzisothiazolinon', 'Benzisothiazolinone', 'rot', 'Reiniger', 'Konservierer – Allergen'),
  ('farbstoff', 'Farbstoff', 'Colourant', 'gelb', 'Reiniger', 'Farbstoffe – unnötig, mögliche Allergene'),
  ('colourant', 'Farbstoff', 'Colourant', 'gelb', 'Reiniger', 'Farbstoffe – unnötig, mögliche Allergene'),
  ('aspergillus niger', 'Aspergillus niger', 'Aspergillus Niger', 'gelb', 'Herstellungsorganismus', 'Aspergillus niger – Schimmelpilz, der industriell zur Fermentation von Zitronensäure und einigen E-Nummern/Enzymen genutzt wird. Herstellungsorganismus, teils gentechnisch verändert (außerhalb EU); Rückstände/Verunreinigungen möglich.'),
  ('aspergillus', 'Aspergillus niger', 'Aspergillus Niger', 'gelb', 'Herstellungsorganismus', 'Aspergillus niger – Schimmelpilz, der industriell zur Fermentation von Zitronensäure und einigen E-Nummern/Enzymen genutzt wird. Herstellungsorganismus, teils gentechnisch verändert (außerhalb EU); Rückstände/Verunreinigungen möglich.')
on conflict (norm_key) do update set d=excluded.d, i=excluded.i, a=excluded.a, k=excluded.k, g=excluded.g;
